// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtE6n2bIT37zdq0MRP1XIvDiLmNU0rzHQ',
    appId: '1:489472674475:web:96fccdc284e92fde1cc5ee',
    messagingSenderId: '489472674475',
    projectId: 'flutter-prueba1-1ebd8',
    authDomain: 'flutter-prueba1-1ebd8.firebaseapp.com',
    storageBucket: 'flutter-prueba1-1ebd8.appspot.com',
    measurementId: 'G-CQ1M6X1W7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQ16TcDH0moPSo7PgAOaj_11jAgpcX0E',
    appId: '1:489472674475:android:4bccc8cb0fae23051cc5ee',
    messagingSenderId: '489472674475',
    projectId: 'flutter-prueba1-1ebd8',
    storageBucket: 'flutter-prueba1-1ebd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWK9VIvc7FWNFWER7A36mr4JzZMVvzwSI',
    appId: '1:489472674475:ios:c0ba92892768f2521cc5ee',
    messagingSenderId: '489472674475',
    projectId: 'flutter-prueba1-1ebd8',
    storageBucket: 'flutter-prueba1-1ebd8.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWK9VIvc7FWNFWER7A36mr4JzZMVvzwSI',
    appId: '1:489472674475:ios:1f0a77a7d945344a1cc5ee',
    messagingSenderId: '489472674475',
    projectId: 'flutter-prueba1-1ebd8',
    storageBucket: 'flutter-prueba1-1ebd8.appspot.com',
    iosBundleId: 'com.example.firebase1.RunnerTests',
  );
}
